#+TITLE:         Assignment 3. The Analytics Edge
#+AUTHOR:        Sergio-Feliciano Mendoza-Barrera
#+DRAWERS:       sfmb
#+EMAIL:         smendoza.barrera@gmail.com
#+DATE:          27/06/2015
#+DESCRIPTION:   Homework week 3 of the analytics edge
#+KEYWORDS:      R, data science, emacs, ESS, org-mode, the analytics edge
#+LANGUAGE:      en
#+OPTIONS:       H:10 num:t toc:nil \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t d:HIDDEN
#+OPTIONS:       TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:       LaTeX:dvipng
#+INFOJS_OPT:    view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+STYLE: <link rel="stylesheet" type="text/css" href="dft.css"/>

#+LaTeX_CLASS: IEEEtran
#+LATEX_CLASS_OPTIONS: [letterpaper, 9pt, onecolumn, twoside, technote, final]
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{makeidx}

#+LATEX_HEADER: \usepackage[lining,tabular]{fbb} % so math uses tabular lining figures
#+LATEX_HEADER: \usepackage[scaled=.95,type1]{cabin} % sans serif in style of Gill Sans
#+LATEX_HEADER: \usepackage[varqu,varl]{zi4}% inconsolata typewriter
#+LATEX_HEADER: \usepackage[T1]{fontenc} % LY1 also works
#+LATEX_HEADER: \usepackage[libertine,bigdelims]{newtxmath}
#+LATEX_HEADER: \usepackage[cal=boondoxo,bb=boondox,frak=boondox]{mathalfa}
#+LATEX_HEADER: \useosf % change normal text to use proportional oldstyle figures

#+LATEX_HEADER: \markboth{Assignment 3}%
#+LATEX_HEADER: {Sergio-Feliciano Mendoza-Barrera}

#+LATEX_HEADER: \newcommand{\degC}{$^\circ$C{}}

#+STYLE: <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"> </script>

#+ATTR_HTML: width="500px"

# -*- mode: org; -*-
#+OPTIONS:   toc:2

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

#+BEGIN_ABSTRACT
This document content the assignment 3 of the third week of The
Analytics Edge course of MIT.
#+END_ABSTRACT

* Popularity of music records

The music industry has a well-developed market with a global annual
revenue around $15$ billion USD. The recording industry is highly
competitive and is dominated by three big production companies which
make up nearly $82\%$ of the total annual album sales.

Artists are at the core of the music industry and record labels
provide them with the necessary resources to sell their music on a
large scale. A record label incurs numerous costs (studio recording,
marketing, distribution, and touring) in exchange for a percentage of
the profits from album sales, singles and concert tickets.

Unfortunately, the success of an artist's release is highly uncertain:
a single may be extremely popular, resulting in widespread radio play
and digital downloads, while another single may turn out quite
unpopular, and therefore unprofitable.

Knowing the competitive nature of the recording industry, record
labels face the fundamental decision problem of which musical releases
to support to maximize their financial success.

How can we use analytics to predict the popularity of a song? In this
assignment, we challenge ourselves to predict whether a song will
reach a spot in the Top 10 of the Billboard Hot 100 Chart.

Taking an analytics approach, we aim to use information about a song's
properties to predict its popularity. The dataset [[https://courses.edx.org/asset-v1:MITx%2B15.071x_2a%2B2T2015%2Btype@asset%2Bblock/songs.csv][songs.csv]] consists
of all songs which made it to the Top 10 of the Billboard Hot 100
Chart from 1990-2010 plus a sample of additional songs that didn't
make the Top 10. This data comes from three sources: [[http://en.wikipedia.org/wiki/Billboard_Hot_100][Wikipedia]],
[[http://www.billboard.com/][Billboard.com]], and [[http://echonest.com][EchoNest]].

The variables included in the dataset either describe the artist or
the song, or they are associated with the following song attributes:
time signature, loudness, key, pitch, tempo, and timbre.

Here's a detailed description of the variables:

    - *year* = the year the song was released

    - *songtitle* = the title of the song

    - *artistname* = the name of the artist of the song

    - *songID* and *artistID* = identifying variables for the song and
      artist

    - *timesignature* and *timesignature_confidence* = a variable
      estimating the time signature of the song, and the confidence in
      the estimate

    - *loudness* = a continuous variable indicating the average
      amplitude of the audio in decibels

    - *tempo* and *tempo_confidence* = a variable indicating the
      estimated beats per minute of the song, and the confidence in
      the estimate

    - *key* and *key_confidence* = a variable with twelve levels
      indicating the estimated key of the song (C, C#, . . ., B), and
      the confidence in the estimate

    - *energy* = a variable that represents the overall acoustic
      energy of the song, using a mix of features such as loudness

    - *pitch* = a continuous variable that indicates the pitch of the
      song

    - *timbre_0_min*, *timbre_0_max*, *timbre_1_min*, *timbre_1_max*,
      ..., *timbre_11_min*, and *timbre_11_max* = variables that
      indicate the minimum/maximum values over all segments for each
      of the twelve values in the timbre vector (resulting in 24
      continuous variables)

    - *Top10* = a binary variable indicating whether or not the song
      made it to the Top 10 of the Billboard Hot 100 Chart (1 if it
      was in the top 10, and 0 if it was not)

** Problem 1.1 - Understanding the Data (1 point possible)

Use the read.csv function to load the dataset "songs.csv" into R.

How many observations (songs) are from the year 2010?
